# Generated by Django 3.1.7 on 2021-03-31 18:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recycle',
            fields=[
                ('id_recycle_point', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_recycle_point', models.CharField(max_length=255)),
                ('name_recycle_point', models.CharField(max_length=255)),
                ('end_recycle_point', models.CharField(max_length=255)),
                ('latitude', models.FloatField(max_length=255)),
                ('longitude', models.FloatField(max_length=255)),
                ('category_recycle_procedure', models.CharField(max_length=255)),
                ('contact_recycle_point', models.CharField(max_length=255)),
                ('info_recycle_point', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
